---
title: "ToolikChlorophyll Concentrations"
author: "Daniel Kerstan"
date: "8/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(here)
library(skimr)
```

## Read in toolik_chlorophyll.csv as a data frame stored as `toolik_chlorophyll`

```{r}
toolik_chlorophyll <- read_csv(here::here("data", "data-raw", "toolik_chlorophyll.csv"), na = ".")

```

```{r}
skim(toolik_chlorophyll)

names(toolik_chlorophyll)



```

```{r}
toolik_chlorophyll <- toolik_chlorophyll %>% clean_names()

names(toolik_chlorophyll)
```

Create a scatterplot of depth versus chlorophyll A concentration 
-make point size `size` changed based on the concentration
-make all points "cyan4"
-update theme to `theme_dark()`
```{r}
chlorophyll_plot <- ggplot(data = toolik_chlorophyll, aes(x = active_chl_a_ug_l, y = depth)) +
  geom_point(aes(size = active_chl_a_ug_l), 
             color = "cyan", alpha = .5) +
  theme_dark() + scale_y_reverse()

chlorophyll_plot
```


```{r}
ggsave(here::here("figs", "chlorophyll_graphs.jpg"), plot = chlorophyll_plot)
```

